add static linking
Better-Player/espeakng-sys pull request #3
Opened 2023-05-06 23:27 UTC by andrewgazelka

2023-05-16 08:16 UTC, TobiasDeBruijn commented
I like this idea!

I do have some questions though:
- Why specific paths for GCC 10 and 11? (and why not 12?)
- Would it not be better to use e.g. pkgconfig on Linux and whatever Windows has? (Does EspeakNG support Windows?)

Thanks!

2023-05-17 00:38 UTC, andrewgazelka commented
yea I need to clean up this PR a bit.

- the specific paths are related to linking std++. I suppose I can include 12. Ideally I would not have to do this. If you are familiar with static linking I would definitely be open to hearing your thoughts as I have not done this a lot before
- when you talk about `pkgconfig` are you refering to https://crates.io/crates/pkg-config?

2023-07-24 19:41 UTC, TobiasDeBruijn requested changes
Apologies for the late reply! Exams took a toll on free time I'm afraid.

Looks good overall, just some minor things!

2023-07-24 19:41 UTC, TobiasDeBruijn commented on build.rs
> +            "https://github.com/espeak-ng/espeak-ng",
We should probably use tags rather than the latest master to avoid breaking down stream users if something changes up-stream (could be a feature?)

2023-07-24 19:41 UTC, TobiasDeBruijn commented on build.rs
> +            "--without-sonic",
Unsure what these do, why should they be disabled?

2025-06-08 05:05 UTC, closed without merging